[versions]
agp = "8.5.0"

androidx-benchmark = "1.2.4"
androidx-test-ext-junit = "1.1.5"
coil = "3.0.0-alpha06"
compose = "1.6.7"
compose-plugin = "1.6.11"
kotlin = "2.0.0"
kotlin-coroutines = "1.8.1"
datetime = "0.6.0"
serialization = "1.6.3"
ktor = "3.0.0-wasm2"
aboutlib = "11.2.1"
kermit = "2.0.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "3.0.1" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenpublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlib" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-collection = "androidx.collection:collection:1.4.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.0"
androidx-compose-ui-test-manifest = "androidx.compose.ui:ui-test-manifest:1.6.8"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.1"
androidx-test-ext-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# sample app
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlib" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlib" }
aboutlibraries-ui = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlib" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# legacy sample app
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-drawerlayout = "androidx.drawerlayout:drawerlayout:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.2"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-activity = "androidx.activity:activity-ktx:1.9.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.2"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.2"
fastadapter = "com.mikepenz:fastadapter:5.7.0"
materialdrawer-core = "com.mikepenz:materialdrawer:9.0.2"
materialdrawer-iconics = "com.mikepenz:materialdrawer-iconics:9.0.1"
iconics-core = "com.mikepenz:iconics-core:5.4.0"
iconics-mdit = "com.mikepenz:material-design-iconic-typeface:2.2.0.8-kotlin"


# Build logic dependencies
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-plugin" }

[bundles]
ktor = ["ktor-core", "ktor-content-negotiation", "ktor-json"]
coil = ["coil-compose", "coil-ktor"]
aboutlibs = ["aboutlibraries-core", "aboutlibraries-compose"]


