[versions]
androidx-benchmark = "1.3.3"
coil = "3.1.0"
kotlin = "2.1.10"
kotlin-coroutines = "1.10.1"
datetime = "0.6.1"
serialization = "1.8.0"
ktor = "3.1.0"
aboutlib = "11.6.3"
kermit = "2.0.5"

[plugins]
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
mavenpublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.10.0"

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# sample app
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlib" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlib" }
aboutlibraries-ui = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlib" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# legacy sample app
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-drawerlayout = "androidx.drawerlayout:drawerlayout:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-activity = "androidx.activity:activity-ktx:1.10.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.7"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7"
fastadapter = "com.mikepenz:fastadapter:5.7.0"
materialdrawer-core = "com.mikepenz:materialdrawer:9.0.2"
materialdrawer-iconics = "com.mikepenz:materialdrawer-iconics:9.0.1"
iconics-core = "com.mikepenz:iconics-core:5.4.0"
iconics-mdit = "com.mikepenz:material-design-iconic-typeface:2.2.0.8-kotlin"

[bundles]
ktor = ["ktor-core", "ktor-content-negotiation", "ktor-json"]
coil = ["coil-compose", "coil-ktor"]
aboutlibs = ["aboutlibraries-core", "aboutlibraries-compose"]


